import pandas as pd
import numpy as np
import featuretools as ft
import os
import argparse
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.linear_model import LinearRegression

# Parse command-line arguments
parser = argparse.ArgumentParser(description='Rank players for recruitment')
parser.add_argument('--alliance', type=str, help='Filter by alliance name (e.g., pstk, SYNZ)')
args = parser.parse_args()

# Read data from CSV file
csv_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'synz.csv')
df = pd.read_csv(csv_path)
# Rename columns to remove units
df = df.rename(columns={'Power (m)': 'Power', 'Kills (m)': 'Kills'})
# Clean data: drop rows with missing essential stats
df = df.dropna(subset=['Member', 'Power', 'Kills', 'Level', 'Prof Lvl', 'Gift Lvl'])

# 1. Setup Featuretools EntitySet
es = ft.EntitySet(id="guild_data")

# Create an entity from the dataframe
# Need to set a unique index for featuretools
df['player_id'] = df['Member'] # Use member name as a unique ID for this example
es.add_dataframe(dataframe_name="players",
                 dataframe=df,
                 index="player_id")

# 2. Run Automated Feature Engineering (AFE)
# This generates many potential features like "SUM(Alliance.Kills)" or "MEAN(Alliance.Power)"
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_dataframe_name="players",
                                      agg_primitives=["sum", "mean", "min", "max", "std"],
                                      verbose=True)

# Add Member and Alliance columns back to feature_matrix for display
feature_matrix['Member'] = df.set_index('player_id')['Member']
feature_matrix['Alliance'] = df.set_index('player_id')['Alliance']

print("\n--- Generated Feature Matrix (Sample of New Composite Scores) ---")
# Display newly generated features alongside original stats
available_cols = [col for col in ['Power', 'Kills', 'Level'] if col in feature_matrix.columns]
print(feature_matrix[available_cols].to_markdown())


# 3. Use an ML model to interpret which generated feature is strongest
# We can define a simple "Target Score" (e.g., a combination of stats)
# Power and level as primary factors, kills as secondary:
# - Power: primary factor (multiplier 2.0)
# - Kills: exponential weighting (power 1.5, multiplier 15) - bonus for activity
# - Level: quadratic with strong multiplier (10.0) - progression heavily valued
feature_matrix['target_strength'] = (feature_matrix['Power'] * 2.0) + \
                                    (np.power(feature_matrix['Kills'], 1.5) * 15) + \
                                    ((feature_matrix['Level'] - 29) ** 2) * 10

# 4. Train a simple Linear Regression model to find a single composite score/coefficient
# This model will try to predict our 'target_strength' using the generated features
features_for_model = feature_matrix.drop(['target_strength'], axis=1).select_dtypes(include=[np.number])
# Clean any NaNs generated by Featuretools for the model
features_for_model = features_for_model.dropna()
target = feature_matrix.loc[features_for_model.index, 'target_strength']

model = LinearRegression()
model.fit(features_for_model, target)

# 5. The resulting 'composite score' is what the linear model predicts
composite_scores = model.predict(features_for_model)
# Normalize to 0-100 scale
min_score = composite_scores.min()
max_score = composite_scores.max()
normalized_scores = ((composite_scores - min_score) / (max_score - min_score)) * 100
feature_matrix.loc[features_for_model.index, 'Composite_Recruit_Score'] = normalized_scores

print("\n--- Top 100 Players Ranked by Composite Recruit Score ---")
ranked_players = feature_matrix.sort_values(by='Composite_Recruit_Score', ascending=False)
display_cols = [col for col in ['Alliance', 'Member', 'Composite_Recruit_Score', 'Level', 'Kills', 'Power'] 
                if col in ranked_players.columns]

# Filter by alliance if specified
if args.alliance:
    ranked_players = ranked_players[ranked_players['Alliance'].str.lower() == args.alliance.lower()]
    print(f"\nFiltered by alliance: {args.alliance}")

# Split into top 100 and consideration list
top_100 = ranked_players.head(100)
consideration = ranked_players.iloc[100:]

# Format and display top 100
display_df = top_100[display_cols].copy()
if 'Composite_Recruit_Score' in display_df.columns:
    display_df['Composite_Recruit_Score'] = display_df['Composite_Recruit_Score'].round(1)
display_df.insert(0, 'Rank', range(1, len(display_df) + 1))
print(display_df.to_markdown(index=False))

# Display consideration list
if len(consideration) > 0:
    print("\n--- Consideration Table (Ranked 101+) ---")
    consideration_df = consideration[display_cols].copy()
    if 'Composite_Recruit_Score' in consideration_df.columns:
        consideration_df['Composite_Recruit_Score'] = consideration_df['Composite_Recruit_Score'].round(1)
    consideration_df.insert(0, 'Rank', range(101, 101 + len(consideration_df)))
    print(consideration_df.to_markdown(index=False))

# Count players by alliance (for top 100)
print("\n--- Player Count by Alliance (Top 100) ---")
top_100_alliance_counts = top_100['Alliance'].value_counts().sort_values(ascending=False)
alliance_df = pd.DataFrame({'Alliance': top_100_alliance_counts.index, 'Count': top_100_alliance_counts.values})
print(alliance_df.to_markdown(index=False))

# Aggregated statistics (for top 100 only)
print("\n--- Aggregated Statistics (Top 100 Players) ---")
total_power = top_100['Power'].sum()
total_kills = top_100['Kills'].sum()
stats_df = pd.DataFrame({'Metric': ['Total Power', 'Total Kills'], 'Value': [f"{total_power:.0f}", f"{total_kills:.2f}"]})
print(stats_df.to_markdown(index=False))

# Count by level (for top 100)
print("\n--- Player Count by Level (Top 100) ---")
level_counts = top_100['Level'].value_counts().sort_values(ascending=False)
